# -*- coding: utf-8 -*-
"""txttopic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMG9NdsP9eW0JtlOyrmFHtZiUowFZIt3
"""

from PIL import Image
import numpy as np
import os

# Load the matrix from the txt file
final_matrix = np.loadtxt('/content/result.txt')

# Define the directory to save the images
save_directory = '/content/'

# Create the directory if it doesn't exist
if not os.path.exists(save_directory):
    os.makedirs(save_directory)

# Iterate over each column and reconstruct the image
for idx in range(final_matrix.shape[1]):
    # Reshape the column data back into a 2D shape
    img_data = final_matrix[:, idx].reshape(256, 192)

    # Convert the data into an image using PIL
    img = Image.fromarray(img_data.astype(np.uint8), 'L')

    # Save the image to the specified directory
    img.save(os.path.join(save_directory, f'restored_image_{idx}.jpg'))